export const PERMISSION_KEYS = {
  ADD_ADMIN: "ADD_ADMIN",
  DELETE_ADMIN: "DELETE_ADMIN",
  UPDATE_ADMIN: "UPDATE_ADMIN",
  
  DELETE_USER: "DELETE_USER",

  ADD_MOVIE: "ADD_MOVIE",
  DELETE_MOVIE: "DELETE_MOVIE",
  UPDATE_MOVIE: "UPDATE_MOVIE",

  ADD_MOVIE_SESSION: "ADD_MOVIE_SESSION",
  DELETE_MOVIE_SESSION: "DELETE_MOVIE_SESSION",
  UPDATE_MOVIE_SESSION: "UPDATE_MOVIE_SESSION",

  ADD_ROOM: "ADD_ROOM",
  DELETE_ROOM: "DELETE_ROOM",

  ADD_LANGUAGE: "ADD_LANGUAGE",
  REMOVE_LANGUAGE: "REMOVE_LANGUAGE",

  ADD_PROFILE_PHOTO_URL: "ADD_PROFILE_PHOTO_URL",
  REMOVE_PROFILE_PHOTO_URL: "REMOVE_PROFILE_PHOTO_URL",
}